### ISSUE TITLE
try example but dont work

### ISSUE THREAD

**Issue by orcim** [robert/how-does-a-tcp-reset-attack-work#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scapy/supersocket.py", line 134, in __del__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 514, in close
    set_promisc(self.ins, self.iface, 0)
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 165, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/linux.py", line 380, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.6/dist-packages/scapy/arch/common.py", line 59, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device

**Comment by robert** [comment]
@orcim could you try this on latest master? I think @squidarth fixed this in https://github.com/robert/how-does-a-tcp-reset-attack-work/pull/2 . Thanks.
