### ISSUE TITLE
Does not complete it's intended use

### ISSUE THREAD

**Issue by blove-sys** [robert/how-does-a-tcp-reset-attack-work#3]
Howdy! I am not sure why this isn't working, but I did take a screen recording of it in use so maybe you can explain. That video file will be attached. Thank you so much, and keep up the great work!

(The video does not seem to be working)

https://user-images.githubusercontent.com/83128135/115963643-3dbe8580-a4ee-11eb-909e-ba28260c8eac.mp4

**Comment by robert** [comment]
For some reason I seem to have made the default be to just log packets instead of running the attack. If you 
uncomment https://github.com/robert/how-does-a-tcp-reset-attack-work/blob/master/main.py#L134-L136 does that help?

**Comment by paul097958** [comment]
I don't think so. I have already done that, but it still has an error.
```
WARNING: No IPv4 address found on anpi0 !
WARNING: No IPv4 address found on anpi1 !
WARNING: more No IPv4 address found on en0 !
Starting sniff... 
Traceback (most recent call last):
  File "/Users/paulwang/Desktop/how-does-a-tcp-reset-attack-work/main.py", line 131, in <module>
    t = sniff(
        ^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/scapy/sendrecv.py", line 1311, in sniff
    sniffer._run(*args, **kwargs)
  File "/opt/homebrew/lib/python3.12/site-packages/scapy/sendrecv.py", line 1250, in _run
    if lfilter and not lfilter(p):
                       ^^^^^^^^^^
  File "/Users/paulwang/Desktop/how-does-a-tcp-reset-attack-work/main.py", line 53, in f
    src_ip = p[IP].src
             ~^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/scapy/packet.py", line 1327, in __getitem__
    raise IndexError("Layer [%s] not found" % name)
IndexError: Layer [IP] not found
```
